/* Finanzas Jóvenes — centro de ahorro y organización */
(function(){
  'use strict';
  const money=n=>'Q '+Number(n||0).toLocaleString('es-GT',{minimumFractionDigits:2,maximumFractionDigits:2});
  const $=(s,r=document)=>r.querySelector(s);

  function addStyles(){
    if($('#fjFinancialHelperStyles'))return;
    const s=document.createElement('style');s.id='fjFinancialHelperStyles';s.textContent=`
#ahorro-inteligente{padding-top:25px!important}
.fj-money-center{background:linear-gradient(145deg,#102218,#FFFAF9);border:1px solid rgba(57,255,136,.18);border-radius:30px;padding:32px;box-shadow:0 25px 75px rgba(0,0,0,.35)}
.fj-money-head{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:22px}.fj-money-head h2{font-size:2.15rem;letter-spacing:-1px}.fj-money-head p{color:#91a199;max-width:680px;margin-top:5px}.fj-money-badge{white-space:nowrap;padding:8px 12px;border-radius:999px;background:#F6EAF0;border:1px solid #CFAFBA;color:#7A1F3D;font-size:.75rem;font-weight:800}
.fj-money-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.fj-money-card{background:rgba(0,0,0,.16);border:1px solid rgba(255,255,255,.07);border-radius:19px;padding:21px}.fj-money-card h3{margin-bottom:5px}.fj-money-card>p{color:#82928a;font-size:.84rem;margin-bottom:15px}.fj-money-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.fj-money-form label{margin:4px 0 5px}.fj-money-form .full{grid-column:1/-1}.fj-money-result{margin-top:15px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.fj-money-stat{padding:13px;background:#0b140e;border:1px solid #23392b;border-radius:13px}.fj-money-stat span{display:block;color:#82928a;font-size:.72rem}.fj-money-stat strong{display:block;color:#7A1F3D;font-size:1.1rem;margin-top:2px}.fj-allocation{margin-top:14px}.fj-alloc-row{margin-top:10px}.fj-alloc-head{display:flex;justify-content:space-between;font-size:.78rem;color:#b8c8bf}.fj-alloc-bar{height:7px;background:#19271f;border-radius:20px;overflow:hidden;margin-top:5px}.fj-alloc-bar div{height:100%;background:linear-gradient(90deg,#54152B,#A94B68);border-radius:20px}
.fj-goal-box{display:grid;gap:10px}.fj-goal-summary{padding:15px;background:#0b140e;border:1px solid #CFAFBA;border-radius:14px}.fj-goal-top{display:flex;justify-content:space-between;gap:10px}.fj-goal-top strong{color:#7A1F3D}.fj-goal-progress{height:11px;background:#19271f;border-radius:20px;overflow:hidden;margin:12px 0 7px}.fj-goal-progress div{height:100%;width:0;background:linear-gradient(90deg,#54152B,#A94B68);border-radius:20px;transition:.35s}.fj-goal-meta{display:flex;justify-content:space-between;color:#87968e;font-size:.75rem}.fj-save-note{color:#87968e;font-size:.75rem;margin-top:8px}.fj-money-actions{display:flex;gap:8px;margin-top:13px;flex-wrap:wrap}.fj-money-actions button{border:1px solid rgba(57,255,136,.18);background:#F6EAF0;color:#7A1F3D;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.fj-money-actions button.secondary{color:#c2cec7;background:#101812;border-color:rgba(255,255,255,.08)}
@media(max-width:900px){#ahorro-inteligente{padding:35px 14px!important}.fj-money-center{padding:18px 12px!important;border-radius:20px!important}.fj-money-head{display:block;margin-bottom:16px}.fj-money-head h2{font-size:1.42rem}.fj-money-head p{font-size:.76rem;line-height:1.5}.fj-money-badge{display:inline-block;margin-top:9px;font-size:.68rem}.fj-money-grid{grid-template-columns:1fr!important;gap:10px}.fj-money-card{padding:14px 12px!important;border-radius:15px}.fj-money-card h3{font-size:1rem}.fj-money-card>p{font-size:.72rem}.fj-money-form{grid-template-columns:1fr!important}.fj-money-form .full{grid-column:auto}.fj-money-form .input{font-size:16px!important;min-height:44px}.fj-money-result{grid-template-columns:1fr 1fr 1fr;gap:5px}.fj-money-stat{padding:10px 7px}.fj-money-stat span{font-size:.61rem}.fj-money-stat strong{font-size:.88rem}.fj-money-actions{display:grid;grid-template-columns:1fr}.fj-money-actions button{width:100%;font-size:.76rem}}
`;
    document.head.appendChild(s);
  }

  function build(){
    if($('#ahorro-inteligente'))return;
    const anchor=$('#herramientas')||$('#panel');if(!anchor||!anchor.parentNode)return;
    addStyles();
    const sec=document.createElement('section');sec.id='ahorro-inteligente';
    sec.innerHTML=`<div class="fj-money-center">
      <div class="fj-money-head"><div><h2>💰 Organiza tu dinero</h2><p>Finanzas Jóvenes no solo te enseña: también te ayuda a planificar tus responsabilidades, separar dinero para ahorrar y saber cuánto tienes disponible.</p></div><span class="fj-money-badge">TU CENTRO DE AHORRO</span></div>
      <div class="fj-money-grid">
        <div class="fj-money-card"><h3>🧮 Distribuye tu ingreso</h3><p>Haz una planificación rápida de lo que recibes cada mes.</p><div class="fj-money-form"><div><label for="fjIncome">Ingreso mensual (Q)</label><input class="input" id="fjIncome" type="number" min="0" step="0.01" placeholder="Ej. 3000"></div><div><label for="fjFixed">Pagos y responsabilidades (Q)</label><input class="input" id="fjFixed" type="number" min="0" step="0.01" placeholder="Ej. 1200"></div><div><label for="fjVariable">Gastos del mes (Q)</label><input class="input" id="fjVariable" type="number" min="0" step="0.01" placeholder="Ej. 800"></div><div><label for="fjSaving">Ahorro que quieres apartar (Q)</label><input class="input" id="fjSaving" type="number" min="0" step="0.01" placeholder="Ej. 500"></div></div><div class="fj-money-result"><div class="fj-money-stat"><span>Responsabilidades</span><strong id="fjFixedOut">Q 0.00</strong></div><div class="fj-money-stat"><span>Ahorro</span><strong id="fjSavingOut">Q 0.00</strong></div><div class="fj-money-stat"><span>Disponible</span><strong id="fjAvailableOut">Q 0.00</strong></div></div><div class="fj-allocation"><div class="fj-alloc-row"><div class="fj-alloc-head"><span>Pagos y responsabilidades</span><span id="fjFixedPct">0%</span></div><div class="fj-alloc-bar"><div id="fjFixedBar" style="width:0"></div></div></div><div class="fj-alloc-row"><div class="fj-alloc-head"><span>Gastos</span><span id="fjVariablePct">0%</span></div><div class="fj-alloc-bar"><div id="fjVariableBar" style="width:0"></div></div></div><div class="fj-alloc-row"><div class="fj-alloc-head"><span>Ahorro</span><span id="fjSavingPct">0%</span></div><div class="fj-alloc-bar"><div id="fjSavingBar" style="width:0"></div></div></div></div><div id="fjBudgetMessage" class="result">Ingresa tus cantidades para comenzar.</div><div class="fj-money-actions"><button id="fjSavePlan">Guardar mi planificación</button><button id="fjClearPlan" class="secondary">Limpiar</button></div></div>
        <div class="fj-money-card"><h3>🎯 Construye una meta de ahorro</h3><p>Define cuánto necesitas y lleva tu progreso contigo.</p><div class="fj-goal-box"><div><label for="fjGoalName">¿Para qué estás ahorrando?</label><input class="input" id="fjGoalName" placeholder="Ej. Laptop, universidad, viaje..."></div><div><label for="fjGoalTarget">¿Cuánto necesitas? (Q)</label><input class="input" id="fjGoalTarget" type="number" min="1" step="0.01" placeholder="Ej. 6000"></div><div><label for="fjGoalCurrent">¿Cuánto tienes ahorrado? (Q)</label><input class="input" id="fjGoalCurrent" type="number" min="0" step="0.01" placeholder="Ej. 2000"></div><div><label for="fjGoalDate">Fecha objetivo</label><input class="input" id="fjGoalDate" type="date"></div><div class="fj-goal-summary"><div class="fj-goal-top"><span id="fjGoalLabel">Mi meta</span><strong id="fjGoalPercent">0%</strong></div><div class="fj-goal-progress"><div id="fjGoalBar"></div></div><div class="fj-goal-meta"><span id="fjGoalSaved">Q 0.00 ahorrados</span><span id="fjGoalRemaining">Q 0.00 faltan</span></div></div><div id="fjGoalMessage" class="result">Completa tu meta para calcular tu progreso.</div><div class="fj-money-actions"><button id="fjSaveGoal">Guardar mi meta</button><button id="fjClearGoal" class="secondary">Limpiar</button></div><div class="fj-save-note">Tus datos de planificación y meta se guardan en este dispositivo para que puedas consultarlos al volver.</div></div></div>
      </div></div>`;
    anchor.parentNode.insertBefore(sec,anchor);
    bind();
    restore();
  }

  function values(){return {income:Number($('#fjIncome')?.value)||0,fixed:Number($('#fjFixed')?.value)||0,variable:Number($('#fjVariable')?.value)||0,saving:Number($('#fjSaving')?.value)||0}}
  function updatePlan(){
    const v=values(),available=v.income-v.fixed-v.variable-v.saving;
    $('#fjFixedOut').textContent=money(v.fixed);$('#fjSavingOut').textContent=money(v.saving);$('#fjAvailableOut').textContent=money(available);
    [['fjFixedPct','fjFixedBar',v.fixed],['fjVariablePct','fjVariableBar',v.variable],['fjSavingPct','fjSavingBar',v.saving]].forEach(([t,b,n])=>{const pct=v.income?Math.max(0,Math.min(100,n/v.income*100)):0;$('#'+t).textContent=Math.round(pct)+'%';$('#'+b).style.width=pct+'%'});
    const msg=$('#fjBudgetMessage');if(!v.income){msg.textContent='Ingresa tus cantidades para comenzar.';msg.className='result';return}if(available<0){msg.textContent='⚠️ Tu planificación supera el ingreso. Revisa pagos, gastos o la cantidad que quieres apartar.';msg.className='result warn'}else if(v.saving>0){msg.textContent='✅ Después de separar tus responsabilidades, gastos y ahorro, te quedarían '+money(available)+' disponibles.';msg.className='result good'}else{msg.textContent='💡 Intenta apartar una cantidad para ahorro antes de gastar el dinero disponible.';msg.className='result'}}
  function updateGoal(){
    const name=$('#fjGoalName').value.trim()||'Mi meta',target=Number($('#fjGoalTarget').value)||0,saved=Number($('#fjGoalCurrent').value)||0,date=$('#fjGoalDate').value;
    const pct=target?Math.max(0,Math.min(100,saved/target*100)):0,remaining=Math.max(0,target-saved);
    $('#fjGoalLabel').textContent=name;$('#fjGoalPercent').textContent=Math.round(pct)+'%';$('#fjGoalBar').style.width=pct+'%';$('#fjGoalSaved').textContent=money(saved)+' ahorrados';$('#fjGoalRemaining').textContent=money(remaining)+' faltan';
    const msg=$('#fjGoalMessage');if(!target){msg.textContent='Completa tu meta para calcular tu progreso.';msg.className='result'}else if(saved>=target){msg.textContent='🎉 ¡Meta alcanzada! Ya llegaste a la cantidad que te propusiste.';msg.className='result good'}else if(date){const days=Math.max(1,Math.ceil((new Date(date+'T00:00:00')-new Date(new Date().toISOString().slice(0,10)+'T00:00:00'))/86400000));msg.textContent='💡 Te faltan '+money(remaining)+'. Para alcanzar la meta en la fecha indicada, serían aproximadamente '+money(remaining/(days/30.44))+' al mes.';msg.className='result'}else{msg.textContent='💡 Te faltan '+money(remaining)+' para alcanzar tu meta.';msg.className='result'}}
  function bind(){
    ['fjIncome','fjFixed','fjVariable','fjSaving'].forEach(id=>$('#'+id).addEventListener('input',updatePlan));
    ['fjGoalName','fjGoalTarget','fjGoalCurrent','fjGoalDate'].forEach(id=>$('#'+id).addEventListener('input',updateGoal));
    $('#fjSavePlan').onclick=()=>{localStorage.setItem('fj_money_plan',JSON.stringify(values()));updatePlan();$('#fjBudgetMessage').textContent='✅ Tu planificación quedó guardada en este dispositivo.'};
    $('#fjClearPlan').onclick=()=>{['fjIncome','fjFixed','fjVariable','fjSaving'].forEach(id=>$('#'+id).value='');localStorage.removeItem('fj_money_plan');updatePlan()};
    $('#fjSaveGoal').onclick=()=>{const g={name:$('#fjGoalName').value,target:Number($('#fjGoalTarget').value)||0,saved:Number($('#fjGoalCurrent').value)||0,date:$('#fjGoalDate').value};localStorage.setItem('fj_savings_goal',JSON.stringify(g));updateGoal();$('#fjGoalMessage').textContent='✅ Tu meta quedó guardada en este dispositivo.'};
    $('#fjClearGoal').onclick=()=>{['fjGoalName','fjGoalTarget','fjGoalCurrent','fjGoalDate'].forEach(id=>$('#'+id).value='');localStorage.removeItem('fj_savings_goal');updateGoal()};
  }
  function restore(){try{const p=JSON.parse(localStorage.getItem('fj_money_plan')||'null');if(p){$('#fjIncome').value=p.income||'';$('#fjFixed').value=p.fixed||'';$('#fjVariable').value=p.variable||'';$('#fjSaving').value=p.saving||''}const g=JSON.parse(localStorage.getItem('fj_savings_goal')||'null');if(g){$('#fjGoalName').value=g.name||'';$('#fjGoalTarget').value=g.target||'';$('#fjGoalCurrent').value=g.saved||'';$('#fjGoalDate').value=g.date||''}}catch(e){}updatePlan();updateGoal()}
  function init(){build()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();