/* Finanzas Jóvenes — Centro de juegos */
(function(){
'use strict';
if(document.getElementById('fjGames')) return;
const style=document.createElement('style');
style.textContent=`
.fj-games-wrap{max-width:1180px;margin:auto;padding:72px 24px}.fj-games-title{text-align:center;margin-bottom:24px}.fj-games-title h2{font-size:2.1rem;margin-bottom:6px}.fj-games-title p{color:#9eafa5}
.fj-level-card{max-width:620px;margin:0 auto 26px;padding:16px 20px;background:linear-gradient(145deg,#152219,#101912);border:1px solid #294034;border-radius:18px;text-align:center;box-shadow:0 12px 35px #0004}.fj-level-name{font-size:1.15rem;font-weight:900;color:#39ff88}.fj-level-points{color:#dce9e1;margin-top:4px}.fj-level-bar{height:8px;background:#0a110d;border-radius:99px;overflow:hidden;margin:10px 0 4px}.fj-level-fill{height:100%;width:0;background:#39ff88;border-radius:99px;transition:.4s}.fj-next{font-size:.75rem;color:#8ea095}
.fj-badges{max-width:950px;margin:0 auto 34px}.fj-badges h3{text-align:center;margin-bottom:14px}.fj-badges-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.fj-badge{padding:14px 8px;border-radius:16px;text-align:center;background:#101812;border:1px solid #263a2c}.fj-badge.unlocked{border-color:#39ff88;box-shadow:0 0 18px #39ff8817}.fj-badge.locked{opacity:.45;filter:grayscale(.8)}.fj-badge-icon{font-size:1.55rem}.fj-badge-name{font-size:.76rem;font-weight:800;margin-top:5px}.fj-badge-state{font-size:.66rem;color:#91a398;margin-top:3px}
.fj-games-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.fj-game{background:linear-gradient(145deg,#152219,#101912);border:1px solid #294034;border-radius:21px;padding:24px;box-shadow:0 12px 35px #0004;transition:.25s;position:relative;overflow:hidden}.fj-game:hover{transform:translateY(-4px);border-color:#3e6a4c}.fj-game-icon{font-size:2.3rem;margin-bottom:8px}.fj-game h3{margin-bottom:5px}.fj-game-desc{color:#9eafa5;font-size:.9rem;min-height:44px}.fj-game-tag{display:inline-block;margin:10px 0 12px;padding:4px 9px;border-radius:999px;background:#0d2517;border:1px solid #28553a;color:#39ff88;font-size:.72rem;font-weight:800}.fj-game-btn{border:0;background:#39ff88;color:#041008;padding:10px 14px;border-radius:12px;font-weight:800;cursor:pointer}.fj-game-btn.alt{background:#132019;color:#39ff88;border:1px solid #355440}.fj-game-area{display:none;margin-top:16px;padding-top:16px;border-top:1px solid #294034}.fj-game-area.show{display:block}.fj-score{color:#39ff88;font-weight:900;margin-bottom:9px}.fj-question{font-weight:800;margin-bottom:10px}.fj-options{display:grid;gap:8px}.fj-option{width:100%;padding:11px;border:1px solid #294034;background:#0a110d;color:#dce9e1;border-radius:11px;text-align:left;cursor:pointer}.fj-option:hover{border-color:#39ff88}.fj-option.good{border-color:#39ff88;background:#0c2918}.fj-option.bad{border-color:#ff6978;background:#291214}
.fj-choice-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.fj-choice{padding:13px;border:1px solid #294034;background:#0a110d;color:#e9f4ed;border-radius:12px;cursor:pointer;text-align:left}.fj-choice:hover{border-color:#39ff88}.fj-choice strong{display:block;color:#39ff88;margin-bottom:3px}.fj-choice small{color:#91a398}.fj-meter{height:12px;background:#09100c;border-radius:99px;overflow:hidden;margin:12px 0}.fj-meter div{height:100%;background:#39ff88;width:0;transition:.3s}.fj-money-row{display:flex;justify-content:space-between;gap:8px;margin:10px 0;color:#dce9e1}.fj-money-box{flex:1;background:#0d2116;border:1px solid #294034;border-radius:12px;padding:10px;text-align:center}.fj-money-box b{display:block;color:#39ff88;font-size:1.05rem}.fj-slider{width:100%;accent-color:#39ff88}.fj-situation{padding:13px;background:#0d2116;border:1px solid #294034;border-radius:12px;line-height:1.45;margin-bottom:10px}.fj-feedback{min-height:40px;margin-top:10px;padding:10px;border-radius:10px;background:#0d2116;color:#baffcf;font-size:.88rem}.fj-coins{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;min-height:105px;padding:10px}.fj-coin{width:48px;height:48px;border:0;border-radius:50%;background:#b5ff63;color:#07100b;font-size:20px;cursor:pointer;box-shadow:0 0 16px #b5ff6330}
@media(max-width:900px){.fj-games-grid{grid-template-columns:1fr}.fj-badges-grid{grid-template-columns:repeat(2,1fr)}.fj-games-wrap{padding:55px 20px}}
`;
document.head.appendChild(style);
const section=document.createElement('section');section.id='juegos';section.className='fj-games-wrap';section.innerHTML=`
<div class="fj-games-title"><h2>🎮 Centro de juegos</h2><p>Retos rápidos para aprender a manejar mejor tu dinero.</p></div>
<div class="fj-level-card"><div class="fj-level-name" id="fjLevelName">🌱 Principiante</div><div class="fj-level-points" id="fjLevelPoints">0 puntos</div><div class="fj-level-bar"><div class="fj-level-fill" id="fjLevelFill"></div></div><div class="fj-next" id="fjLevelNext">Juega para ganar puntos y subir de nivel.</div></div>
<div class="fj-badges"><h3>🏅 Mis logros</h3><div class="fj-badges-grid" id="fjBadgesGrid"></div></div>
<div class="fj-games-grid">
<article class="fj-game"><div class="fj-game-icon">🛒</div><h3>Compra inteligente</h3><p class="fj-game-desc">Tienes dinero limitado. Elige qué comprar primero y descubre si tu decisión ayuda o afecta tu presupuesto.</p><span class="fj-game-tag">Decisiones · +10 pts</span><br><button class="fj-game-btn" onclick="fjSmartStart()">Empezar</button><div id="fjSmartArea" class="fj-game-area"><div class="fj-score" id="fjSmartScore">Ronda 1 de 5</div><div class="fj-situation" id="fjSmartQ"></div><div class="fj-choice-grid" id="fjSmartOptions"></div></div></article>
<article class="fj-game"><div class="fj-game-icon">💸</div><h3>Arma tu presupuesto</h3><p class="fj-game-desc">Mueve las barras y reparte Q1,000 entre necesidades, ahorro y gustos.</p><span class="fj-game-tag">Interactivo · +15 pts</span><br><button class="fj-game-btn" onclick="fjBudgetStart()">Empezar</button><div id="fjBudgetArea" class="fj-game-area"><div class="fj-money-row"><div class="fj-money-box">Necesidades<b id="fjNVal">Q500</b></div><div class="fj-money-box">Ahorro<b id="fjSVal">Q300</b></div><div class="fj-money-box">Gustos<b id="fjWVal">Q200</b></div></div><label>Necesidades</label><input class="fj-slider" id="fjNSlider" type="range" min="0" max="1000" value="500"><label>Ahorro</label><input class="fj-slider" id="fjSSlider" type="range" min="0" max="1000" value="300"><div class="fj-feedback" id="fjBudgetFeedback">La suma debe ser exactamente Q1,000.</div><button class="fj-game-btn" style="margin-top:9px" onclick="fjBudgetCheck()">Comprobar</button></div></article>
<article class="fj-game"><div class="fj-game-icon">🚦</div><h3>Semáforo de gastos</h3><p class="fj-game-desc">Lee una situación y decide: 🟢 buena decisión, 🟡 piénsalo, o 🔴 mejor evitarla.</p><span class="fj-game-tag">5 decisiones · +10 pts</span><br><button class="fj-game-btn" onclick="fjLightStart()">Empezar</button><div id="fjLightArea" class="fj-game-area"><div class="fj-score" id="fjLightScore">0 / 5</div><div class="fj-situation" id="fjLightQ"></div><div class="fj-choice-grid"><button class="fj-choice" onclick="fjLightAnswer('verde')"><strong>🟢 Verde</strong><small>Es una decisión razonable.</small></button><button class="fj-choice" onclick="fjLightAnswer('amarillo')"><strong>🟡 Amarillo</strong><small>Conviene pensarlo antes.</small></button><button class="fj-choice" onclick="fjLightAnswer('rojo')"><strong>🔴 Rojo</strong><small>Puede perjudicar el presupuesto.</small></button></div></div></article>
<article class="fj-game"><div class="fj-game-icon">🪙</div><h3>Reto de ahorro</h3><p class="fj-game-desc">Atrapa monedas durante 15 segundos. Cada moneda representa una pequeña cantidad que podrías apartar.</p><span class="fj-game-tag">15 segundos · hasta +15 pts</span><br><button class="fj-game-btn" onclick="fjCoinStart()">Empezar</button><div id="fjCoinArea" class="fj-game-area"><div class="fj-score" id="fjCoinScore">Monedas: 0 · Tiempo: 15</div><div class="fj-coins" id="fjCoins"></div></div></article>
</div>`;
const panel=document.getElementById('panel');if(panel)panel.parentNode.insertBefore(section,panel);else document.querySelector('main')?.appendChild(section);
const nav=document.querySelector('header nav > div:nth-child(2)');if(nav&&!nav.querySelector('a[href="#juegos"]')){const link=document.createElement('a');link.href='#juegos';link.textContent='🎮 Juegos';const retos=nav.querySelector('a[href="#interactivo"]');retos?nav.insertBefore(link,retos):nav.appendChild(link)}
const logo=document.querySelector('.logo');if(logo){logo.style.textAlign='center';logo.style.paddingLeft='7px';logo.style.paddingRight='7px';logo.style.fontSize='1.13rem';logo.style.whiteSpace='nowrap'}
const levels=[{name:'🌱 Principiante',min:0,next:50},{name:'💵 Ahorrador',min:50,next:150},{name:'📊 Organizado',min:150,next:300},{name:'🏆 Experto financiero',min:300,next:null}];
const badges=[{key:'first_game',icon:'🥉',name:'Primer juego',desc:'Completa tu primer reto'},{key:'fifty_points',icon:'💰',name:'50 puntos',desc:'Consigue 50 puntos'},{key:'three_games',icon:'🔥',name:'Racha inicial',desc:'Juega 3 veces'},{key:'organized',icon:'📊',name:'Organizado',desc:'Llega a 150 puntos'},{key:'expert',icon:'🏆',name:'Experto financiero',desc:'Llega a 300 puntos'}];
let gamePoints=0,gamePlayedCount=0;
function renderLevel(){const l=[...levels].reverse().find(x=>gamePoints>=x.min)||levels[0],n=l.next;document.getElementById('fjLevelName').textContent=l.name;document.getElementById('fjLevelPoints').textContent=gamePoints+' puntos';document.getElementById('fjLevelFill').style.width=n?Math.min(100,(gamePoints-l.min)/(n-l.min)*100)+'%':'100%';document.getElementById('fjLevelNext').textContent=n?'Faltan '+Math.max(0,n-gamePoints)+' puntos para el siguiente nivel.':'¡Nivel máximo alcanzado!'}
function renderBadges(unlocked=[]){const set=new Set(unlocked);document.getElementById('fjBadgesGrid').innerHTML=badges.map(b=>`<div class="fj-badge ${set.has(b.key)?'unlocked':'locked'}"><div class="fj-badge-icon">${set.has(b.key)?b.icon:'🔒'}</div><div class="fj-badge-name">${b.name}</div><div class="fj-badge-state">${set.has(b.key)?'Desbloqueado':b.desc}</div></div>`).join('')}
async function loadProgress(){renderBadges([]);try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data}=await window.supabaseClient.from('game_progress').select('points,games_played').eq('user_id',session.user.id).maybeSingle();gamePoints=data?.points||0;gamePlayedCount=data?.games_played||0;const {data:earned}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);renderBadges((earned||[]).map(x=>x.badge_key));renderLevel()}catch(e){renderLevel()}}
async function unlockBadges(){try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data:earned}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);const set=new Set((earned||[]).map(x=>x.badge_key));const wanted=[];if(gamePlayedCount>=1)wanted.push('first_game');if(gamePoints>=50)wanted.push('fifty_points');if(gamePlayedCount>=3)wanted.push('three_games');if(gamePoints>=150)wanted.push('organized');if(gamePoints>=300)wanted.push('expert');for(const key of wanted)if(!set.has(key))await window.supabaseClient.from('game_badges').insert({user_id:session.user.id,badge_key:key});const {data:now}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);renderBadges((now||[]).map(x=>x.badge_key))}catch(e){console.warn(e)}}
async function awardPoints(amount){gamePoints+=amount;gamePlayedCount++;renderLevel();try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data:old}=await window.supabaseClient.from('game_progress').select('points,games_played,games_won').eq('user_id',session.user.id).maybeSingle();await window.supabaseClient.from('game_progress').upsert({user_id:session.user.id,points:gamePoints,games_played:(old?.games_played||0)+1,games_won:(old?.games_won||0)+1,updated_at:new Date().toISOString()},{onConflict:'user_id'});gamePlayedCount=(old?.games_played||0)+1;await unlockBadges()}catch(e){console.warn('No se pudo guardar el progreso',e)}}
loadProgress();
const smart=[['Necesitas Q100 para transporte esta semana y ves unos audífonos de Q90 en oferta.','Usar el dinero en transporte','Comprar los audífonos'],['Ya tienes comida para hoy y recibes Q50 extra.','Guardar una parte','Gastar todo sin pensarlo'],['Tu celular funciona bien, pero aparece uno nuevo que te gusta.','Ahorrar para una meta','Comprar inmediatamente'],['Necesitas un cuaderno para estudiar y tienes Q30.','Comprar el cuaderno','Comprar un accesorio que no necesitas'],['Tienes una meta de ahorro y recibes dinero inesperado.','Apartar una parte para la meta','Gastar todo porque llegó de sorpresa']];let si=0,ss=0;
window.fjSmartStart=function(){si=0;ss=0;document.getElementById('fjSmartArea').classList.add('show');fjSmartPaint()};function fjSmartPaint(){const x=smart[si];document.getElementById('fjSmartScore').textContent='Ronda '+(si+1)+' de 5 · '+ss+' aciertos';document.getElementById('fjSmartQ').textContent=x[0];document.getElementById('fjSmartOptions').innerHTML=[x[1],x[2]].map((o,i)=>`<button class="fj-choice" onclick="fjSmartAnswer(${i})"><strong>${i?'🛍️':'💚'} ${o}</strong><small>Elige la opción que cuida mejor tu dinero.</small></button>`).join('')}
window.fjSmartAnswer=function(i){if(i===0)ss++;si++;if(si<smart.length){fjSmartPaint()}else{document.getElementById('fjSmartScore').textContent='Resultado: '+ss+' / 5';document.getElementById('fjSmartQ').textContent=ss>=4?'🎉 ¡Muy buenas decisiones! Ganaste 10 puntos.':'💡 Buen intento. Piensa en tus necesidades y metas antes de gastar.';document.getElementById('fjSmartOptions').innerHTML='<button class="fj-game-btn alt" onclick="fjSmartStart()">Jugar de nuevo</button>';if(ss>=4)awardPoints(10)}};
const ns=document.getElementById('fjNSlider'),ssli=document.getElementById('fjSSlider');function fjBudgetPaint(){let n=+ns.value,s=+ssli.value;if(n+s>1000){if(document.activeElement===ns)n=1000-s;else s=1000-n;if(n<0)n=0;if(s<0)s=0}const w=1000-n-s;ns.value=n;ssli.value=s;document.getElementById('fjNVal').textContent='Q'+n;document.getElementById('fjSVal').textContent='Q'+s;document.getElementById('fjWVal').textContent='Q'+w;document.getElementById('fjBudgetFeedback').textContent=w>=100&&s>=150&&n>=400?'👍 Se ve equilibrado. ¡Compruébalo!':'💡 Intenta cubrir necesidades, ahorrar una parte y dejar algo para gustos.'}window.fjBudgetStart=function(){document.getElementById('fjBudgetArea').classList.add('show');fjBudgetPaint()};ns.addEventListener('input',fjBudgetPaint);ssli.addEventListener('input',fjBudgetPaint);let budgetWon=false;window.fjBudgetCheck=function(){let n=+ns.value,s=+ssli.value,w=1000-n-s,r=document.getElementById('fjBudgetFeedback');if(n>=400&&s>=150&&w>=100){r.textContent='🎉 ¡Buen equilibrio! Ganaste 15 puntos.';if(!budgetWon){budgetWon=true;awardPoints(15)}}else r.textContent='🔎 Ajusta las barras: primero cubre necesidades, luego reserva ahorro y deja una cantidad para gustos.'};
const lights=[['Te dan Q50 y tienes una meta de ahorro. Guardas Q30 y usas Q20 en algo que querías.','verde'],['Compras algo porque todos tus amigos lo tienen, aunque no lo necesitas.','rojo'],['Antes de comprar, comparas precios y revisas si cabe en tu presupuesto.','verde'],['Usas dinero reservado para una meta en una compra impulsiva.','rojo'],['Quieres comprar algo y decides esperar un día para pensarlo.','amarillo']];let li=0,ls=0;
window.fjLightStart=function(){li=0;ls=0;document.getElementById('fjLightArea').classList.add('show');fjLightPaint()};function fjLightPaint(){document.getElementById('fjLightScore').textContent=ls+' / 5';document.getElementById('fjLightQ').textContent=lights[li][0]}window.fjLightAnswer=function(v){if(v===lights[li][1])ls++;li++;if(li<lights.length)fjLightPaint();else{document.getElementById('fjLightScore').textContent='Resultado: '+ls+' / 5';document.getElementById('fjLightQ').textContent=ls>=4?'🎉 ¡Excelente! Ganaste 10 puntos.':'💡 Revisa tus decisiones y vuelve a intentarlo.';if(ls>=4)awardPoints(10)}};
let timer=null,coins=0,time=15;window.fjCoinStart=function(){clearInterval(timer);coins=0;time=15;document.getElementById('fjCoinArea').classList.add('show');fjCoinPaint();timer=setInterval(()=>{time--;fjCoinPaint();if(time<=0){clearInterval(timer);document.getElementById('fjCoins').innerHTML='<strong>⏰ ¡Tiempo!</strong><br><button class="fj-game-btn alt" onclick="fjCoinStart()">Jugar de nuevo</button>';if(coins)awardPoints(Math.min(15,coins))}},1000)};function fjCoinPaint(){document.getElementById('fjCoinScore').textContent='Monedas: '+coins+' · Tiempo: '+time;const box=document.getElementById('fjCoins');box.innerHTML='';if(time<=0)return;for(let i=0;i<Math.min(8,4+Math.floor(Math.random()*5));i++){const b=document.createElement('button');b.className='fj-coin';b.textContent='Q';b.onclick=()=>{coins++;b.remove();document.getElementById('fjCoinScore').textContent='Monedas: '+coins+' · Tiempo: '+time};box.appendChild(b)}}
})();
