/* Finanzas Jóvenes — Centro de juegos arcade */
(function(){
'use strict';
if(document.getElementById('fjGames')) return;

const style=document.createElement('style');
style.textContent=`
.fj-games-wrap{max-width:1180px;margin:auto;padding:72px 24px}.fj-games-title{text-align:center;margin-bottom:26px}.fj-games-title h2{font-size:2.2rem;margin:0 0 6px}.fj-games-title p{color:#9eafa5}
.fj-level-card{max-width:650px;margin:0 auto 28px;padding:17px 20px;background:linear-gradient(145deg,#152219,#101912);border:1px solid #294034;border-radius:20px;text-align:center;box-shadow:0 12px 35px #0004}.fj-level-name{font-size:1.18rem;font-weight:900;color:#39ff88}.fj-level-points{color:#dce9e1;margin-top:4px}.fj-level-bar{height:9px;background:#0a110d;border-radius:99px;overflow:hidden;margin:10px 0 4px}.fj-level-fill{height:100%;width:0;background:#39ff88;border-radius:99px;transition:.4s}.fj-next{font-size:.75rem;color:#8ea095}
.fj-badges{max-width:950px;margin:0 auto 34px}.fj-badges h3{text-align:center;margin-bottom:14px}.fj-badges-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.fj-badge{padding:13px 8px;border-radius:16px;text-align:center;background:#101812;border:1px solid #263a2c}.fj-badge.unlocked{border-color:#39ff88;box-shadow:0 0 18px #39ff8817}.fj-badge.locked{opacity:.42;filter:grayscale(.8)}.fj-badge-icon{font-size:1.5rem}.fj-badge-name{font-size:.76rem;font-weight:800;margin-top:5px}.fj-badge-state{font-size:.65rem;color:#91a398;margin-top:3px}
.fj-games-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.fj-game{background:linear-gradient(145deg,#152219,#101912);border:1px solid #294034;border-radius:22px;padding:22px;box-shadow:0 12px 35px #0004;transition:.25s;position:relative;overflow:hidden}.fj-game:hover{transform:translateY(-4px);border-color:#3e6a4c}.fj-game-icon{font-size:2.5rem;margin-bottom:6px}.fj-game h3{margin:0 0 5px}.fj-game-desc{color:#9eafa5;font-size:.9rem;min-height:42px}.fj-game-tag{display:inline-block;margin:9px 0 12px;padding:4px 9px;border-radius:999px;background:#0d2517;border:1px solid #28553a;color:#39ff88;font-size:.72rem;font-weight:800}.fj-game-btn{border:0;background:#39ff88;color:#041008;padding:10px 15px;border-radius:12px;font-weight:900;cursor:pointer;transition:.2s}.fj-game-btn:hover{transform:scale(1.04);box-shadow:0 0 18px #39ff8840}.fj-game-area{display:none;margin-top:16px;padding-top:16px;border-top:1px solid #294034}.fj-game-area.show{display:block}.fj-score{color:#39ff88;font-weight:900;margin-bottom:9px}.fj-arcade{position:relative;height:250px;background:radial-gradient(circle at center,#15321f,#07100b 70%);border:1px solid #294034;border-radius:18px;overflow:hidden;cursor:crosshair;user-select:none}.fj-hud{display:flex;justify-content:space-between;padding:9px 12px;font-size:.82rem;font-weight:900;position:absolute;top:0;left:0;right:0;z-index:5;background:#06100bd9}.fj-target{position:absolute;border:0;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:transform .12s}.fj-target:hover{transform:scale(1.12)}.fj-coin-target{width:48px;height:48px;border-radius:50%;background:#b5ff63;color:#07100b;font-size:22px;box-shadow:0 0 20px #b5ff6350}.fj-bill-target{width:60px;height:38px;border-radius:9px;background:#39ff88;color:#06100b;font-size:20px;box-shadow:0 0 18px #39ff8840}.fj-bad-target{width:54px;height:54px;border-radius:14px;background:#ff5364;color:#21070b;font-size:24px;box-shadow:0 0 18px #ff536450}.fj-cart{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);font-size:48px;line-height:1;transition:left .08s;z-index:4}.fj-road{position:absolute;left:0;right:0;bottom:0;height:72px;background:repeating-linear-gradient(90deg,#14251a 0 42px,#1d3825 42px 84px);border-top:2px solid #294034}.fj-road-line{position:absolute;top:32px;left:0;right:0;border-top:3px dashed #b5ff63}
.fj-memory{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:6px}.fj-card{height:62px;border:1px solid #294034;border-radius:12px;background:#09120d;color:#39ff88;font-size:1.7rem;cursor:pointer}.fj-card.hidden{font-size:0}.fj-card.hidden:after{content:'?';font-size:1.4rem;color:#668172}.fj-card.matched{background:#12301d;border-color:#39ff88}
.fj-pig{height:250px;position:relative;border-radius:18px;background:radial-gradient(circle,#183a24,#07100b 72%);border:1px solid #294034;overflow:hidden}.fj-pig-img{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:95px;transition:.15s}.fj-falling{position:absolute;font-size:30px;cursor:pointer;animation:fjFall linear forwards;z-index:3}.fj-pop{position:absolute;font-weight:900;color:#39ff88;animation:fjPop .65s ease-out forwards;pointer-events:none;z-index:6}.fj-shake{animation:fjShake .25s}.fj-result{padding:14px;border-radius:14px;background:#0d2116;border:1px solid #294034;text-align:center;margin-top:10px;color:#dce9e1}.fj-result b{color:#39ff88;font-size:1.2rem}
@keyframes fjFall{from{top:-40px}to{top:280px}}@keyframes fjPop{from{opacity:1;transform:translateY(0) scale(1)}to{opacity:0;transform:translateY(-35px) scale(1.25)}}@keyframes fjShake{25%{transform:translate(-53%,-50%)}75%{transform:translate(-47%,-50%)}}
@media(max-width:900px){.fj-games-grid{grid-template-columns:1fr}.fj-badges-grid{grid-template-columns:repeat(2,1fr)}.fj-games-wrap{padding:55px 20px}}
`;
document.head.appendChild(style);

const section=document.createElement('section');
section.id='fjGames';section.className='fj-games-wrap';
section.innerHTML=`
<div class="fj-games-title"><h2>🎮 Centro de juegos</h2><p>Juega, diviértete y consigue puntos dentro de Finanzas Jóvenes.</p></div>
<div class="fj-level-card"><div class="fj-level-name" id="fjLevelName">🌱 Principiante</div><div class="fj-level-points" id="fjLevelPoints">0 puntos</div><div class="fj-level-bar"><div class="fj-level-fill" id="fjLevelFill"></div></div><div class="fj-next" id="fjLevelNext">Juega para ganar puntos y subir de nivel.</div></div>
<div class="fj-badges"><h3>🏅 Mis logros</h3><div class="fj-badges-grid" id="fjBadgesGrid"></div></div>
<div class="fj-games-grid">
<article class="fj-game"><div class="fj-game-icon">🪙</div><h3>Atrapa las monedas</h3><p class="fj-game-desc">Haz clic en monedas y billetes que aparecen por la pantalla. ¡Pero cuidado con los gastos!</p><span class="fj-game-tag">30 segundos · arcade</span><br><button class="fj-game-btn" onclick="fjCoinsStart()">▶ Jugar</button><div id="fjCoinsArea" class="fj-game-area"><div class="fj-arcade" id="fjCoinsBoard"><div class="fj-hud"><span id="fjCoinsScore">🪙 0</span><span id="fjCoinsTime">⏱️ 30</span></div></div></div></article>
<article class="fj-game"><div class="fj-game-icon">🛒</div><h3>Carrito loco</h3><p class="fj-game-desc">Mueve el carrito con el mouse o las flechas y atrapa el dinero mientras esquivas los gastos.</p><span class="fj-game-tag">30 segundos · habilidad</span><br><button class="fj-game-btn" onclick="fjCartStart()">▶ Jugar</button><div id="fjCartArea" class="fj-game-area"><div class="fj-arcade" id="fjCartBoard"><div class="fj-hud"><span id="fjCartScore">💰 0</span><span id="fjCartTime">⏱️ 30</span></div><div class="fj-road"><div class="fj-road-line"></div></div><div class="fj-cart" id="fjCart">🛒</div></div></div></article>
<article class="fj-game"><div class="fj-game-icon">🐷</div><h3>Alimenta la alcancía</h3><p class="fj-game-desc">Atrapa monedas y billetes para llenar tu alcancía. Consigue combos para sumar más.</p><span class="fj-game-tag">20 segundos · combos</span><br><button class="fj-game-btn" onclick="fjPigStart()">▶ Jugar</button><div id="fjPigArea" class="fj-game-area"><div class="fj-pig" id="fjPigBoard"><div class="fj-pig-img" id="fjPig">🐷</div></div></div></article>
<article class="fj-game"><div class="fj-game-icon">🧠</div><h3>Memoria del dinero</h3><p class="fj-game-desc">Voltea las cartas y encuentra todas las parejas. Un juego clásico con temática financiera.</p><span class="fj-game-tag">12 cartas · memoria</span><br><button class="fj-game-btn" onclick="fjMemoryStart()">▶ Jugar</button><div id="fjMemoryArea" class="fj-game-area"><div class="fj-score" id="fjMemoryScore">Parejas: 0 / 6</div><div class="fj-memory" id="fjMemory"></div></div></article>
</div>`;
const panel=document.getElementById('panel');if(panel)panel.parentNode.insertBefore(section,panel);else document.querySelector('main')?.appendChild(section);

const nav=document.querySelector('header nav > div:nth-child(2)');
if(nav&&!nav.querySelector('a[href="#juegos"]')){const link=document.createElement('a');link.href='#juegos';link.textContent='🎮 Juegos';const retos=nav.querySelector('a[href="#interactivo"]');retos?nav.insertBefore(link,retos):nav.appendChild(link)}
const logo=document.querySelector('.logo');if(logo){logo.style.textAlign='center';logo.style.paddingLeft='7px';logo.style.paddingRight='7px';logo.style.fontSize='1.13rem';logo.style.whiteSpace='nowrap'}

const levels=[{name:'🌱 Principiante',min:0,next:50},{name:'💵 Ahorrador',min:50,next:150},{name:'📊 Organizado',min:150,next:300},{name:'🏆 Experto financiero',min:300,next:null}];
const badges=[{key:'first_game',icon:'🥉',name:'Primer juego',desc:'Completa tu primer juego'},{key:'fifty_points',icon:'💰',name:'50 puntos',desc:'Consigue 50 puntos'},{key:'three_games',icon:'🔥',name:'Racha inicial',desc:'Juega 3 veces'},{key:'organized',icon:'📊',name:'Organizado',desc:'Llega a 150 puntos'},{key:'expert',icon:'🏆',name:'Experto financiero',desc:'Llega a 300 puntos'}];
let gamePoints=0,gamePlayedCount=0;
function renderLevel(){const l=[...levels].reverse().find(x=>gamePoints>=x.min)||levels[0],n=l.next;document.getElementById('fjLevelName').textContent=l.name;document.getElementById('fjLevelPoints').textContent=gamePoints+' puntos';document.getElementById('fjLevelFill').style.width=n?Math.min(100,(gamePoints-l.min)/(n-l.min)*100)+'%':'100%';document.getElementById('fjLevelNext').textContent=n?'Faltan '+Math.max(0,n-gamePoints)+' puntos para el siguiente nivel.':'¡Nivel máximo alcanzado!'}
function renderBadges(unlocked=[]){const set=new Set(unlocked);document.getElementById('fjBadgesGrid').innerHTML=badges.map(b=>`<div class="fj-badge ${set.has(b.key)?'unlocked':'locked'}"><div class="fj-badge-icon">${set.has(b.key)?b.icon:'🔒'}</div><div class="fj-badge-name">${b.name}</div><div class="fj-badge-state">${set.has(b.key)?'Desbloqueado':b.desc}</div></div>`).join('')}
async function loadProgress(){renderBadges([]);renderLevel();try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data}=await window.supabaseClient.from('game_progress').select('points,games_played').eq('user_id',session.user.id).maybeSingle();gamePoints=data?.points||0;gamePlayedCount=data?.games_played||0;const {data:earned}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);renderBadges((earned||[]).map(x=>x.badge_key));renderLevel()}catch(e){console.warn(e)}}
async function awardPoints(amount){gamePoints+=amount;gamePlayedCount++;renderLevel();try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data:old}=await window.supabaseClient.from('game_progress').select('points,games_played,games_won').eq('user_id',session.user.id).maybeSingle();await window.supabaseClient.from('game_progress').upsert({user_id:session.user.id,points:gamePoints,games_played:(old?.games_played||0)+1,games_won:(old?.games_won||0)+1,updated_at:new Date().toISOString()},{onConflict:'user_id'});gamePlayedCount=(old?.games_played||0)+1;unlockBadges()}catch(e){console.warn(e)}}
async function unlockBadges(){try{const {data:{session}}=await window.supabaseClient.auth.getSession();if(!session)return;const {data:earned}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);const set=new Set((earned||[]).map(x=>x.badge_key));const wanted=[];if(gamePlayedCount>=1)wanted.push('first_game');if(gamePoints>=50)wanted.push('fifty_points');if(gamePlayedCount>=3)wanted.push('three_games');if(gamePoints>=150)wanted.push('organized');if(gamePoints>=300)wanted.push('expert');for(const key of wanted)if(!set.has(key))await window.supabaseClient.from('game_badges').insert({user_id:session.user.id,badge_key:key});const {data:now}=await window.supabaseClient.from('game_badges').select('badge_key').eq('user_id',session.user.id);renderBadges((now||[]).map(x=>x.badge_key))}catch(e){console.warn(e)}}

function pop(board,text,x,y){const p=document.createElement('div');p.className='fj-pop';p.textContent=text;p.style.left=x+'px';p.style.top=y+'px';board.appendChild(p);setTimeout(()=>p.remove(),650)}
function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min}

let coinTimer=null,coinSpawn=null,coinScore=0,coinTime=30;
window.fjCoinsStart=function(){clearInterval(coinTimer);clearInterval(coinSpawn);coinScore=0;coinTime=30;const board=document.getElementById('fjCoinsBoard');document.getElementById('fjCoinsArea').classList.add('show');board.querySelectorAll('.fj-target').forEach(x=>x.remove());document.getElementById('fjCoinsScore').textContent='🪙 0';document.getElementById('fjCoinsTime').textContent='⏱️ 30';
const spawn=()=>{const good=Math.random()>.22,b=document.createElement('button');b.className='fj-target '+(good?(Math.random()>.5?'fj-coin-target':'fj-bill-target'):'fj-bad-target');b.textContent=good?(b.classList.contains('fj-bill-target')?'💵':'🪙'):'💸';b.style.left=rand(12,88)+'%';b.style.top=rand(45,82)+'%';b.onclick=()=>{const x=b.offsetLeft,y=b.offsetTop;if(good){coinScore+=b.classList.contains('fj-bill-target')?20:10;pop(board,'+'+(b.classList.contains('fj-bill-target')?20:10),x,y)}else{coinScore=Math.max(0,coinScore-15);pop(board,'-15',x,y)}document.getElementById('fjCoinsScore').textContent='🪙 '+coinScore;b.remove()};board.appendChild(b);setTimeout(()=>b.remove(),1200)};
spawn();coinSpawn=setInterval(spawn,430);coinTimer=setInterval(()=>{coinTime--;document.getElementById('fjCoinsTime').textContent='⏱️ '+coinTime;if(coinTime<=0){clearInterval(coinTimer);clearInterval(coinSpawn);board.querySelectorAll('.fj-target').forEach(x=>x.remove());const pts=coinScore>=100?15:coinScore>=60?10:coinScore>=30?5:0;pop(board,'¡Fin! +'+pts+' pts',board.clientWidth/2-35,120);if(pts)awardPoints(pts)}},1000)};

let cartTimer=null,cartSpawn=null,cartScore=0,cartTime=30,cartX=50;
window.fjCartStart=function(){clearInterval(cartTimer);clearInterval(cartSpawn);cartScore=0;cartTime=30;cartX=50;const board=document.getElementById('fjCartBoard'),cart=document.getElementById('fjCart');document.getElementById('fjCartArea').classList.add('show');board.querySelectorAll('.fj-target').forEach(x=>x.remove());cart.style.left='50%';document.getElementById('fjCartScore').textContent='💰 0';document.getElementById('fjCartTime').textContent='⏱️ 30';
const move=e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')cartX=Math.max(7,cartX-6);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')cartX=Math.min(93,cartX+6);cart.style.left=cartX+'%'};document.onkeydown=move;board.onmousemove=e=>{const r=board.getBoundingClientRect();cartX=Math.max(7,Math.min(93,((e.clientX-r.left)/r.width)*100));cart.style.left=cartX+'%'};
const spawn=()=>{const good=Math.random()>.3,b=document.createElement('button');b.className='fj-target '+(good?'fj-bill-target':'fj-bad-target');b.textContent=good?'💵':'🧾';b.style.left=rand(8,92)+'%';b.style.top='42px';b.onclick=()=>{cartScore+=good?10:-10;cartScore=Math.max(0,cartScore);document.getElementById('fjCartScore').textContent='💰 '+cartScore;b.remove()};board.appendChild(b);let y=42;const fall=setInterval(()=>{y+=7;b.style.top=y+'px';const br=b.getBoundingClientRect(),cr=cart.getBoundingClientRect();if(br.bottom>=cr.top&&br.left<cr.right&&br.right>cr.left){clearInterval(fall);b.click()}if(y>230){clearInterval(fall);b.remove()}},70)};
cartSpawn=setInterval(spawn,550);cartTimer=setInterval(()=>{cartTime--;document.getElementById('fjCartTime').textContent='⏱️ '+cartTime;if(cartTime<=0){clearInterval(cartTimer);clearInterval(cartSpawn);board.querySelectorAll('.fj-target').forEach(x=>x.remove());document.onkeydown=null;const pts=cartScore>=120?15:cartScore>=70?10:cartScore>=30?5:0;if(pts)awardPoints(pts)}},1000)};

let pigTimer=null,pigSpawn=null,pigScore=0,pigCombo=0,pigTime=20;
window.fjPigStart=function(){clearInterval(pigTimer);clearInterval(pigSpawn);pigScore=0;pigCombo=0;pigTime=20;const board=document.getElementById('fjPigBoard');const pig=document.getElementById('fjPig');document.getElementById('fjPigArea').classList.add('show');board.querySelectorAll('.fj-falling,.fj-result').forEach(x=>x.remove());pig.textContent='🐷';
const spawn=()=>{const good=Math.random()>.2,b=document.createElement('div');b.className='fj-falling';b.textContent=good?(Math.random()>.45?'🪙':'💵'):'💸';b.style.left=rand(8,88)+'%';b.style.animationDuration=rand(1200,1900)/1000+'s';b.onclick=()=>{b.remove();if(good){pigCombo++;const gain=pigCombo%5===0?20:5;pigScore+=gain;pop(board,'+'+gain,b.offsetLeft,b.offsetTop)}else{pigCombo=0;pigScore=Math.max(0,pigScore-10);pig.classList.add('fj-shake');setTimeout(()=>pig.classList.remove('fj-shake'),250)}};board.appendChild(b);setTimeout(()=>b.remove(),2000)};pigSpawn=setInterval(spawn,420);pigTimer=setInterval(()=>{pigTime--;if(pigTime<=0){clearInterval(pigTimer);clearInterval(pigSpawn);board.querySelectorAll('.fj-falling').forEach(x=>x.remove());const pts=pigScore>=100?15:pigScore>=60?10:pigScore>=30?5:0;const r=document.createElement('div');r.className='fj-result';r.innerHTML='🐷 Resultado: <b>'+pigScore+'</b> puntos de juego'+(pts?' · +'+pts+' XP':'');board.appendChild(r);if(pts)awardPoints(pts)}},1000)};

let memoryFirst=null,memoryLock=false,memoryPairs=0,memoryMoves=0;
window.fjMemoryStart=function(){const box=document.getElementById('fjMemory'),area=document.getElementById('fjMemoryArea');area.classList.add('show');box.innerHTML='';memoryFirst=null;memoryLock=false;memoryPairs=0;memoryMoves=0;document.getElementById('fjMemoryScore').textContent='Parejas: 0 / 6';const icons=['🪙','💵','🐷','🏦','🎯','💰'];const deck=[...icons,...icons].sort(()=>Math.random()-.5);deck.forEach((icon,i)=>{const b=document.createElement('button');b.className='fj-card hidden';b.dataset.icon=icon;b.dataset.i=i;b.textContent=icon;b.onclick=()=>fjMemoryFlip(b);box.appendChild(b)})};
window.fjMemoryFlip=function(card){if(memoryLock||card===memoryFirst||!card.classList.contains('hidden'))return;card.classList.remove('hidden');if(!memoryFirst){memoryFirst=card;return}memoryMoves++;if(memoryFirst.dataset.icon===card.dataset.icon){memoryFirst.classList.add('matched');card.classList.add('matched');memoryPairs++;memoryFirst=null;document.getElementById('fjMemoryScore').textContent='Parejas: '+memoryPairs+' / 6';if(memoryPairs===6){const pts=memoryMoves<=10?15:memoryMoves<=16?10:5;setTimeout(()=>{document.getElementById('fjMemoryScore').textContent='🎉 ¡Completado! +'+pts+' XP';awardPoints(pts)},250)}}else{memoryLock=true;setTimeout(()=>{memoryFirst.classList.add('hidden');card.classList.add('hidden');memoryFirst=null;memoryLock=false},650)}};

loadProgress();
})();