/* Finanzas Jóvenes — navegación, PWA y experiencia móvil */
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function addStyles(){if($('#fjMobileStyles'))return;const s=document.createElement('style');s.id='fjMobileStyles';s.textContent=`
.fj-install-overlay{position:fixed!important;inset:0!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:20px!important;background:rgba(0,0,0,.78)!important;backdrop-filter:blur(9px)!important;z-index:99999!important}.fj-install-card{width:min(430px,100%)!important;padding:32px 28px!important;border-radius:28px!important;background:linear-gradient(145deg,#13291b,#07100b)!important;border:1px solid rgba(57,255,136,.28)!important;text-align:center!important;color:#f4faf6!important}.fj-install-logo{width:72px!important;height:72px!important;margin:0 auto 16px!important;display:flex!important;align-items:center!important;justify-content:center!important;border-radius:22px!important;background:rgba(57,255,136,.09)!important;font-size:2.2rem!important}.fj-install-card h2{font-size:1.8rem!important;margin:0 0 8px!important}.fj-install-card h2 span{color:#39ff88!important}.fj-install-card>p{color:#9eafa5!important;font-size:.94rem!important;line-height:1.6!important;margin:0 auto 23px!important;max-width:340px!important}.fj-install-actions{display:grid!important;gap:10px!important}.fj-install-actions button{width:100%!important;border-radius:14px!important;padding:14px 16px!important;font-size:.95rem!important;font-weight:800!important;cursor:pointer!important}.fj-install-main{background:#39ff88!important;color:#041008!important;border:1px solid #39ff88!important}.fj-install-web{background:rgba(255,255,255,.035)!important;color:#dce9e1!important;border:1px solid rgba(255,255,255,.10)!important}
@media(max-width:900px){body{padding-left:0!important;padding-bottom:94px!important;overflow-x:hidden!important}header{display:none!important}main{width:100%!important;overflow:hidden!important}.hero{min-height:auto!important;display:flex!important;flex-direction:column!important;gap:4px!important;padding:38px 16px 34px!important}.hero-visual{width:100%!important;min-height:300px!important;margin-top:17px!important}.money-card{width:calc(100% - 18px)!important;max-width:390px!important;padding:21px!important;border-radius:22px!important;transform:none!important}h1{font-size:clamp(2.35rem,12vw,3.7rem)!important;line-height:1.02!important;overflow-wrap:anywhere!important}.hero p{font-size:.96rem!important;line-height:1.55!important}.hero-buttons{display:grid!important;grid-template-columns:1fr!important;gap:9px!important}.hero .button{width:100%!important;text-align:center!important}.features,.tools,.dashboard-grid,.dash-content{grid-template-columns:1fr!important;gap:13px!important}.feature,.panel{width:100%!important;min-width:0!important}.expense-form{grid-template-columns:1fr!important}.expense-form .button{width:100%!important}.dashboard{padding:20px!important;border-radius:20px!important}.dashboard-grid{gap:8px!important}.quick-actions{display:grid!important;grid-template-columns:1fr!important;gap:8px!important}.quick-actions .button,.quick-actions .nav-button{width:100%!important}.cta{padding:38px 18px!important;border-radius:21px!important}footer{padding-bottom:110px!important}#fjChatbot,#fjChatbotButton{bottom:94px!important;max-width:calc(100vw - 24px)!important}}
@media(max-width:380px){.fj-install-card{padding:26px 20px!important}}
`;document.head.appendChild(s)}
function removeInteractive(){const el=$('#interactivo');if(el)el.remove();$$('a[href="#interactivo"]').forEach(a=>a.remove());$$('.hero-buttons a').forEach(a=>{if(a.getAttribute('href')==='#interactivo'){a.href='#pagos';a.textContent='Ver mis recordatorios 🔔'}});const hero=$('.hero p');if(hero&&hero.textContent.includes('supera retos'))hero.textContent='Aprende a manejar tu dinero de una forma sencilla, organiza tus gastos, registra tus pagos y empieza a construir buenos hábitos financieros.'}
function pwa(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.json';document.head.appendChild(l)}if(!document.querySelector('meta[name="theme-color"]')){const m=document.createElement('meta');m.name='theme-color';m.content='#39ff88';document.head.appendChild(m)}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
async function installPrompt(){if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)return;if(localStorage.getItem('fj_app_installed')==='1'||localStorage.getItem('fj_install_prompt_seen')==='1')return;localStorage.setItem('fj_install_prompt_seen','1');let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e},{once:true});setTimeout(()=>{const o=document.createElement('div');o.className='fj-install-overlay';o.innerHTML='<div class="fj-install-card"><div class="fj-install-logo">💚</div><h2>Finanzas <span>Jóvenes</span></h2><p>Aprende a manejar tu dinero de forma fácil, organiza tus pagos y lleva tus metas contigo.</p><div class="fj-install-actions"><button class="fj-install-main">📲 Instalar aplicación</button><button class="fj-install-web">🌐 Continuar en la página</button></div></div>';document.body.appendChild(o);o.querySelector('.fj-install-web').onclick=()=>o.remove();o.querySelector('.fj-install-main').onclick=async()=>{if(!deferred){o.remove();return}try{await deferred.prompt();await deferred.userChoice;localStorage.setItem('fj_app_installed','1')}catch(e){}o.remove()};window.addEventListener('appinstalled',()=>{localStorage.setItem('fj_app_installed','1');o.remove()},{once:true})},700)}
function loadScript(src,key){if($('script[data-'+key+']'))return;const s=document.createElement('script');s.src=src;s.dataset[key]='true';document.head.appendChild(s)}
function loadSharedMenu(){return new Promise(resolve=>{if(document.querySelector('script[data-fj-shared-menu]')||window.__fjSharedMenuLoaded){resolve();return}const s=document.createElement('script');s.src='profile-menu-sync.js?v=5';s.dataset.fjSharedMenu='true';s.onload=()=>{window.__fjSharedMenuLoaded=true;resolve()};s.onerror=()=>resolve();document.head.appendChild(s)})}
async function init(){await loadSharedMenu();addStyles();removeInteractive();pwa();loadScript('./auth-fix.js?v=1','fj-auth-fix');loadScript('./notifications.js?v=2','fj-notifications');loadScript('./payments.js?v=1','fj-payments');installPrompt();if(sessionStorage.getItem('fj_open_login')==='1'){sessionStorage.removeItem('fj_open_login');setTimeout(()=>{if(typeof window.openAuth==='function')window.openAuth('login')},250)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();