/* Finanzas Jóvenes — navegación, PWA y experiencia móvil */
(function(){
  'use strict';
  const SUPABASE_URL='https://pgfgmxeqisrwkrwtvbum.supabase.co';
  const SUPABASE_KEY='sb_publishable_6al9XSM0nTc6-RlkX2UUrw_SLaQdwEh';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function addStyles(){if($('#fjMobileStyles'))return;const s=document.createElement('style');s.id='fjMobileStyles';s.textContent=`
.fj-mobile-nav{display:none;position:fixed!important;left:10px!important;right:10px!important;bottom:10px!important;height:68px!important;padding:7px!important;align-items:stretch!important;justify-content:space-around!important;gap:4px!important;background:rgba(8,17,12,.96)!important;border:1px solid rgba(57,255,136,.22)!important;border-radius:22px!important;box-shadow:0 15px 45px rgba(0,0,0,.55),0 0 25px rgba(57,255,136,.08)!important;backdrop-filter:blur(18px)!important;z-index:9998!important}.fj-mobile-nav button{flex:1!important;min-width:0!important;border:0!important;background:transparent!important;color:#8fa197!important;border-radius:16px!important;font-size:.66rem!important;font-weight:800!important;cursor:pointer!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important;line-height:1.15!important}.fj-mobile-nav button span{font-size:1.18rem!important}.fj-mobile-nav button.active{background:rgba(57,255,136,.12)!important;color:#39ff88!important}.fj-desktop-profile,.fj-desktop-payments{display:flex!important}.fj-install-overlay{position:fixed!important;inset:0!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:20px!important;background:rgba(0,0,0,.78)!important;backdrop-filter:blur(9px)!important;z-index:99999!important}.fj-install-card{width:min(430px,100%)!important;padding:32px 28px!important;border-radius:28px!important;background:linear-gradient(145deg,#13291b,#07100b)!important;border:1px solid rgba(57,255,136,.28)!important;text-align:center!important;color:#f4faf6!important}.fj-install-logo{width:72px!important;height:72px!important;margin:0 auto 16px!important;display:flex!important;align-items:center!important;justify-content:center!important;border-radius:22px!important;background:rgba(57,255,136,.09)!important;font-size:2.2rem!important}.fj-install-card h2{font-size:1.8rem!important;margin:0 0 8px!important}.fj-install-card h2 span{color:#39ff88!important}.fj-install-card>p{color:#9eafa5!important;font-size:.94rem!important;line-height:1.6!important;margin:0 auto 23px!important;max-width:340px!important}.fj-install-actions{display:grid!important;gap:10px!important}.fj-install-actions button{width:100%!important;border-radius:14px!important;padding:14px 16px!important;font-size:.95rem!important;font-weight:800!important;cursor:pointer!important}.fj-install-main{background:#39ff88!important;color:#041008!important;border:1px solid #39ff88!important}.fj-install-web{background:rgba(255,255,255,.035)!important;color:#dce9e1!important;border:1px solid rgba(255,255,255,.10)!important}
@media(max-width:900px){body{padding-left:0!important;padding-bottom:94px!important;overflow-x:hidden!important}header{display:none!important}.fj-mobile-nav{display:flex!important}main{width:100%!important;overflow:hidden!important}.hero{min-height:auto!important;display:flex!important;flex-direction:column!important;gap:4px!important;padding:38px 16px 34px!important}.hero-visual{width:100%!important;min-height:300px!important;margin-top:17px!important}.money-card{width:calc(100% - 18px)!important;max-width:390px!important;padding:21px!important;border-radius:22px!important;transform:none!important}h1{font-size:clamp(2.35rem,12vw,3.7rem)!important;line-height:1.02!important;overflow-wrap:anywhere!important}.hero p{font-size:.96rem!important;line-height:1.55!important}.hero-buttons{display:grid!important;grid-template-columns:1fr!important;gap:9px!important}.hero .button{width:100%!important;text-align:center!important}.features,.tools,.dashboard-grid,.dash-content{grid-template-columns:1fr!important;gap:13px!important}.feature,.panel{width:100%!important;min-width:0!important}.expense-form{grid-template-columns:1fr!important}.expense-form .button{width:100%!important}.dashboard{padding:20px!important;border-radius:20px!important}.dashboard-grid{gap:8px!important}.quick-actions{display:grid!important;grid-template-columns:1fr!important;gap:8px!important}.quick-actions .button,.quick-actions .nav-button{width:100%!important}.cta{padding:38px 18px!important;border-radius:21px!important}footer{padding-bottom:110px!important}#fjChatbot,#fjChatbotButton{bottom:94px!important;max-width:calc(100vw - 24px)!important}}
@media(max-width:380px){.fj-mobile-nav{left:6px!important;right:6px!important;bottom:6px!important;height:65px!important}.fj-mobile-nav button{font-size:.57rem!important}.fj-mobile-nav button span{font-size:1.05rem!important}}
@media(min-width:901px){.fj-desktop-profile,.fj-desktop-payments{display:flex!important}}
`;document.head.appendChild(s)}
  function removeInteractive(){const el=$('#interactivo');if(el)el.remove();$$('a[href="#interactivo"]').forEach(a=>a.remove());const heroButtons=$$('.hero-buttons a');heroButtons.forEach(a=>{if(a.getAttribute('href')==='#interactivo'){a.href='#pagos';a.textContent='Ver mis recordatorios 🔔'}});const hero=$('.hero p');if(hero&&hero.textContent.includes('supera retos'))hero.textContent='Aprende a manejar tu dinero de una forma sencilla, organiza tus gastos, registra tus pagos y empieza a construir buenos hábitos financieros.'}
  function addDesktopMenu(){const menu=$('header nav div:nth-child(2)');if(!menu)return false;$$('a[href="#interactivo"]',menu).forEach(a=>a.remove());const fin=$('a[href="#herramientas"]',menu);if(fin)fin.innerHTML='💰 Finanzas';let panel=$('a[href="#panel"]',menu);if(!panel)return false;let pagos=$('a[href="#pagos"]',menu);if(!pagos){pagos=document.createElement('a');pagos.href='#pagos';pagos.className='fj-desktop-payments';menu.appendChild(pagos)}pagos.innerHTML='🔔 Recordatorios';let perfil=$('a[href="./profile.html"]',menu);if(!perfil){perfil=document.createElement('a');perfil.href='./profile.html';perfil.className='fj-desktop-profile';menu.appendChild(perfil)}perfil.innerHTML='👤 Perfil';menu.appendChild(perfil);menu.appendChild(pagos);return true}
  function addMobileNav(){if($('.fj-mobile-nav'))return;const nav=document.createElement('nav');nav.className='fj-mobile-nav';nav.setAttribute('aria-label','Navegación móvil');[['inicio','🏠','Inicio'],['aprende','📚','Aprende'],['herramientas','💰','Finanzas'],['panel','📊','Mi panel'],['perfil','👤','Perfil'],['pagos','🔔','Recordatorios']].forEach(([id,icon,label])=>{const b=document.createElement('button');b.type='button';b.dataset.target=id;b.innerHTML='<span>'+icon+'</span>'+label;b.addEventListener('click',()=>{if(id==='perfil'){if(b.dataset.logged==='1')location.href='./profile.html';else window.openAuth?.('login');return}const el=$('#'+id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});setActive(id)});nav.appendChild(b)});document.body.appendChild(nav);setActive('inicio')}
  function setActive(id){$$('.fj-mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===id))}
  function profileMenu(logged){const b=$('.fj-mobile-nav button[data-target="perfil"]');if(b){b.dataset.logged=logged?'1':'0';b.innerHTML=logged?'<span>👤</span>Perfil':'<span>🔐</span>Iniciar sesión'}}
  async function authWatcher(){profileMenu(false);try{if(!window.supabase)return;const c=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const sync=async()=>{const {data}=await c.auth.getUser();profileMenu(!!data?.user);const d=$('.fj-desktop-profile');if(d)d.style.display=data?.user?'flex':'none'};await sync();c.auth.onAuthStateChange((_e,s)=>profileMenu(!!s?.user))}catch(e){}}
  function observe(){if(!('IntersectionObserver'in window))return;const io=new IntersectionObserver(es=>{const x=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(x)setActive(x.target.id)},{rootMargin:'-25% 0px -55% 0px',threshold:[.05,.2,.5]});['inicio','aprende','herramientas','panel','pagos'].forEach(id=>{const e=$('#'+id);if(e)io.observe(e)})}
  function pwa(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.json';document.head.appendChild(l)}if(!document.querySelector('meta[name="theme-color"]')){const m=document.createElement('meta');m.name='theme-color';m.content='#39ff88';document.head.appendChild(m)}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
  async function installPrompt(){if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)return;if(localStorage.getItem('fj_app_installed')==='1'||localStorage.getItem('fj_install_prompt_seen')==='1')return;localStorage.setItem('fj_install_prompt_seen','1');let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e},{once:true});setTimeout(()=>{const o=document.createElement('div');o.className='fj-install-overlay';o.innerHTML='<div class="fj-install-card"><div class="fj-install-logo">💚</div><h2>Finanzas <span>Jóvenes</span></h2><p>Aprende a manejar tu dinero de forma fácil, organiza tus pagos y lleva tus metas contigo.</p><div class="fj-install-actions"><button class="fj-install-main">📲 Instalar aplicación</button><button class="fj-install-web">🌐 Continuar en la página</button></div></div>';document.body.appendChild(o);o.querySelector('.fj-install-web').onclick=()=>o.remove();o.querySelector('.fj-install-main').onclick=async()=>{if(!deferred){o.remove();return}try{await deferred.prompt();await deferred.userChoice;localStorage.setItem('fj_app_installed','1')}catch(e){}o.remove()};window.addEventListener('appinstalled',()=>{localStorage.setItem('fj_app_installed','1');o.remove()},{once:true})},700)}
  function loadScript(src,key){if($('script[data-'+key+']'))return;const s=document.createElement('script');s.src=src;s.dataset[key]='true';document.head.appendChild(s)}
  function init(){addStyles();removeInteractive();addMobileNav();addDesktopMenu();authWatcher();observe();pwa();loadScript('./notifications.js?v=2','fj-notifications');loadScript('./payments.js?v=1','fj-payments');installPrompt()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();